QT += widgets
qtHaveModule(printsupport): QT += printsupport

SOURCES += \
    scribble.cpp \
    main.cpp \
    mainwindow.cpp \
    compute_volume.cpp \
    transform_2_jpeg.cpp \
    ../../../Imebra/library/base/src/baseObject.cpp \
    ../../../Imebra/library/base/src/baseStream.cpp \
    ../../../Imebra/library/base/src/charsetConversionBase.cpp \
    ../../../Imebra/library/base/src/charsetConversionIconv.cpp \
    ../../../Imebra/library/base/src/charsetConversionICU.cpp \
    ../../../Imebra/library/base/src/charsetConversionWindows.cpp \
    ../../../Imebra/library/base/src/criticalSection.cpp \
    ../../../Imebra/library/base/src/exception.cpp \
    ../../../Imebra/library/base/src/huffmanTable.cpp \
    ../../../Imebra/library/base/src/memory.cpp \
    ../../../Imebra/library/base/src/memoryStream.cpp \
    ../../../Imebra/library/base/src/stream.cpp \
    ../../../Imebra/library/base/src/streamController.cpp \
    ../../../Imebra/library/base/src/streamReader.cpp \
    ../../../Imebra/library/base/src/streamWriter.cpp \
    ../../../Imebra/library/imebra/src/applyLUT.cpp \
    ../../../Imebra/library/imebra/src/buffer.cpp \
    ../../../Imebra/library/imebra/src/charsetsList.cpp \
    ../../../Imebra/library/imebra/src/codec.cpp \
    ../../../Imebra/library/imebra/src/codecFactory.cpp \
    ../../../Imebra/library/imebra/src/colorTransform.cpp \
    ../../../Imebra/library/imebra/src/colorTransformsFactory.cpp \
    ../../../Imebra/library/imebra/src/data.cpp \
    ../../../Imebra/library/imebra/src/dataGroup.cpp \
    ../../../Imebra/library/imebra/src/dataHandler.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerDate.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerDateTime.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerDateTimeBase.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerString.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringAE.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringAS.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringCS.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringDS.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringIS.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringLO.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringLT.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringPN.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringSH.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringST.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringUI.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringUnicode.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerStringUT.cpp \
    ../../../Imebra/library/imebra/src/dataHandlerTime.cpp \
    ../../../Imebra/library/imebra/src/dataSet.cpp \
    ../../../Imebra/library/imebra/src/dicomCodec.cpp \
    ../../../Imebra/library/imebra/src/dicomDict.cpp \
    ../../../Imebra/library/imebra/src/dicomDir.cpp \
    ../../../Imebra/library/imebra/src/drawBitmap.cpp \
    ../../../Imebra/library/imebra/src/image.cpp \
    ../../../Imebra/library/imebra/src/jpegCodec.cpp \
    ../../../Imebra/library/imebra/src/LUT.cpp \
    ../../../Imebra/library/imebra/src/modalityVOILUT.cpp \
    ../../../Imebra/library/imebra/src/MONOCHROME1ToMONOCHROME2.cpp \
    ../../../Imebra/library/imebra/src/MONOCHROME1ToRGB.cpp \
    ../../../Imebra/library/imebra/src/MONOCHROME2ToRGB.cpp \
    ../../../Imebra/library/imebra/src/MONOCHROME2ToYBRFULL.cpp \
    ../../../Imebra/library/imebra/src/PALETTECOLORToRGB.cpp \
    ../../../Imebra/library/imebra/src/RGBToMONOCHROME2.cpp \
    ../../../Imebra/library/imebra/src/RGBToYBRFULL.cpp \
    ../../../Imebra/library/imebra/src/RGBToYBRPARTIAL.cpp \
    ../../../Imebra/library/imebra/src/transaction.cpp \
    ../../../Imebra/library/imebra/src/transform.cpp \
    ../../../Imebra/library/imebra/src/transformHighBit.cpp \
    ../../../Imebra/library/imebra/src/transformsChain.cpp \
    ../../../Imebra/library/imebra/src/viewHelper.cpp \
    ../../../Imebra/library/imebra/src/VOILUT.cpp \
    ../../../Imebra/library/imebra/src/waveform.cpp \
    ../../../Imebra/library/imebra/src/YBRFULLToMONOCHROME2.cpp \
    ../../../Imebra/library/imebra/src/YBRFULLToRGB.cpp \
    ../../../Imebra/library/imebra/src/YBRPARTIALToRGB.cpp

HEADERS += \
    scribble.h \
    mainwindow.h \
    compute_volume.h \
    transform_2_jpeg.h \
    ../../../Imebra/library/base/include/baseObject.h \
    ../../../Imebra/library/base/include/baseStream.h \
    ../../../Imebra/library/base/include/charsetConversion.h \
    ../../../Imebra/library/base/include/charsetConversionBase.h \
    ../../../Imebra/library/base/include/charsetConversionIconv.h \
    ../../../Imebra/library/base/include/charsetConversionICU.h \
    ../../../Imebra/library/base/include/charsetConversionWindows.h \
    ../../../Imebra/library/base/include/configuration.h \
    ../../../Imebra/library/base/include/criticalSection.h \
    ../../../Imebra/library/base/include/exception.h \
    ../../../Imebra/library/base/include/huffmanTable.h \
    ../../../Imebra/library/base/include/memory.h \
    ../../../Imebra/library/base/include/memoryStream.h \
    ../../../Imebra/library/base/include/nullStream.h \
    ../../../Imebra/library/base/include/stream.h \
    ../../../Imebra/library/base/include/streamController.h \
    ../../../Imebra/library/base/include/streamReader.h \
    ../../../Imebra/library/base/include/streamWriter.h \
    ../../../Imebra/library/imebra/include/applyLUT.h \
    ../../../Imebra/library/imebra/include/buffer.h \
    ../../../Imebra/library/imebra/include/bufferStream.h \
    ../../../Imebra/library/imebra/include/charsetsList.h \
    ../../../Imebra/library/imebra/include/codec.h \
    ../../../Imebra/library/imebra/include/codecFactory.h \
    ../../../Imebra/library/imebra/include/colorTransform.h \
    ../../../Imebra/library/imebra/include/colorTransformsFactory.h \
    ../../../Imebra/library/imebra/include/data.h \
    ../../../Imebra/library/imebra/include/dataCollection.h \
    ../../../Imebra/library/imebra/include/dataGroup.h \
    ../../../Imebra/library/imebra/include/dataHandler.h \
    ../../../Imebra/library/imebra/include/dataHandlerDate.h \
    ../../../Imebra/library/imebra/include/dataHandlerDateTime.h \
    ../../../Imebra/library/imebra/include/dataHandlerDateTimeBase.h \
    ../../../Imebra/library/imebra/include/dataHandlerNumeric.h \
    ../../../Imebra/library/imebra/include/dataHandlerString.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringAE.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringAS.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringCS.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringDS.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringIS.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringLO.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringLT.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringPN.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringSH.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringST.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringUI.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringUnicode.h \
    ../../../Imebra/library/imebra/include/dataHandlerStringUT.h \
    ../../../Imebra/library/imebra/include/dataHandlerTime.h \
    ../../../Imebra/library/imebra/include/dataSet.h \
    ../../../Imebra/library/imebra/include/dicomCodec.h \
    ../../../Imebra/library/imebra/include/dicomDict.h \
    ../../../Imebra/library/imebra/include/dicomDir.h \
    ../../../Imebra/library/imebra/include/drawBitmap.h \
    ../../../Imebra/library/imebra/include/image.h \
    ../../../Imebra/library/imebra/include/imebra.h \
    ../../../Imebra/library/imebra/include/imebraDoc.h \
    ../../../Imebra/library/imebra/include/jpegCodec.h \
    ../../../Imebra/library/imebra/include/LUT.h \
    ../../../Imebra/library/imebra/include/modalityVOILUT.h \
    ../../../Imebra/library/imebra/include/MONOCHROME1ToMONOCHROME2.h \
    ../../../Imebra/library/imebra/include/MONOCHROME1ToRGB.h \
    ../../../Imebra/library/imebra/include/MONOCHROME2ToRGB.h \
    ../../../Imebra/library/imebra/include/MONOCHROME2ToYBRFULL.h \
    ../../../Imebra/library/imebra/include/PALETTECOLORToRGB.h \
    ../../../Imebra/library/imebra/include/RGBToMONOCHROME2.h \
    ../../../Imebra/library/imebra/include/RGBToYBRFULL.h \
    ../../../Imebra/library/imebra/include/RGBToYBRPARTIAL.h \
    ../../../Imebra/library/imebra/include/transaction.h \
    ../../../Imebra/library/imebra/include/transform.h \
    ../../../Imebra/library/imebra/include/transformHighBit.h \
    ../../../Imebra/library/imebra/include/transformsChain.h \
    ../../../Imebra/library/imebra/include/viewHelper.h \
    ../../../Imebra/library/imebra/include/VOILUT.h \
    ../../../Imebra/library/imebra/include/waveform.h \
    ../../../Imebra/library/imebra/include/YBRFULLToMONOCHROME2.h \
    ../../../Imebra/library/imebra/include/YBRFULLToRGB.h \
    ../../../Imebra/library/imebra/include/YBRPARTIALToRGB.h
